#if !defined ( IDENTIFIANTS_H )
#define IDENTIFIANTS_H

class Identifiants{

public:
	enum 
	{
		ID_SYMBOLE =0,
		ID_ADDITION,
		ID_SOUSTRACTION,
		ID_MULTIPLICATION,
		ID_DIVISION,
		ID_OUVREPARENTHESE,
		ID_FERMEPARENTHESE,
		ID_LIRE,
		ID_ECRIRE,
		ID_VAR,
		ID_CONST,
		ID_VIRGULE,
		ID_POINTVIRGULE,
		ID_ID,
		ID_EGAL,
		ID_AFFECTATION,
		ID_ENDOFFILE,
		ID_PROGRAMME,
		ID_PARTIEDECLARATIVE,
		ID_PARTIEINSTRUCTIVE,
		ID_DECLARATION,
		ID_INSTRUCTION,
		ID_DECLARATIONVARIABLE,
		ID_DECLARATIONCONSTANTE,
		ID_INSTRUCTIONAFFECTATION,
		ID_INSTRUCTIONECRIRE,
		ID_INSTRUCTIONLIRE,
		ID_EXPRESSION,
		ID_NOMBRE,
		ID_CONSTANTE,
		ID_VARIABLE,
		ID_EXPRESSIONADDITIVE,
		ID_EXPRESSIONMULTIPLICATIVE,
		ID_EXPRESSIONPARENTHESEE,
		ID_OPERATIONADDITIVE,
		ID_OPERATIONMULTIPLICATIVE
	};

};

#endif 